[package]
name = "kime-window"
version = "0.1.0"
authors = ["Riey <creeper844@gmail.com>"]
edition = "2018"
license = "GPL-3.0"

[profile.release]
lto = true

[dependencies]
ahash = "0.7.1"
glib = "0.10.3"
gtk = "0.9.2"
include-flate = "0.1.3"
zbus = "1.8.0"
zvariant = "2.5.0"

